### ISSUE TITLE
[Feature] goal 입력, subgoal 조회

### ISSUE THREAD

**Issue by Haewonny** [GDSC-snowflowerthon/Blooming-team10-server#3]
### 🚀 Feature
> 목표(goal) 입력, AI 6가지 세부목표(subgoal) 생성 결과 조회

### ✅ Tasks
- [x] OpenAI API 연동
- [x] 파인튜닝 모델 테스트
- [x] 목표 입력
- [x] AI 세부목표 생성 결과 조회
- [x] goal, subgoal 엔티티 생성
- [x] API test
